/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as StoreRouteImport } from './routes/_store'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PainelLojaOldRouteImport } from './routes/painel-loja.old'
import { Route as PainelLojaLojaIdRouteImport } from './routes/painel-loja.$lojaId'
import { Route as InscricaoTokenRouteImport } from './routes/inscricao.$token'
import { Route as AdminVariacoesRouteImport } from './routes/admin/variacoes'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as AdminSelosRouteImport } from './routes/admin/selos'
import { Route as AdminRelatoriosRouteImport } from './routes/admin/relatorios'
import { Route as AdminProdutosRouteImport } from './routes/admin/produtos'
import { Route as AdminPerguntasRouteImport } from './routes/admin/perguntas'
import { Route as AdminPbmsRouteImport } from './routes/admin/pbms'
import { Route as AdminPaginasInformativasRouteImport } from './routes/admin/paginas-informativas'
import { Route as AdminMinhaLogisticaRouteImport } from './routes/admin/minha-logistica'
import { Route as AdminMetricasRouteImport } from './routes/admin/metricas'
import { Route as AdminMarcasRouteImport } from './routes/admin/marcas'
import { Route as AdminLogisticaRouteImport } from './routes/admin/logistica'
import { Route as AdminListaEsperaRouteImport } from './routes/admin/lista-espera'
import { Route as AdminLinksCarrinhoRouteImport } from './routes/admin/links-carrinho'
import { Route as AdminIntegracoesRouteImport } from './routes/admin/integracoes'
import { Route as AdminFiltrosRouteImport } from './routes/admin/filtros'
import { Route as AdminEstoqueRouteImport } from './routes/admin/estoque'
import { Route as AdminDescontosRouteImport } from './routes/admin/descontos'
import { Route as AdminColecoesRouteImport } from './routes/admin/colecoes'
import { Route as AdminCategoriasRouteImport } from './routes/admin/categorias'
import { Route as AdminCarrinhosAbandonadosRouteImport } from './routes/admin/carrinhos-abandonados'
import { Route as AdminBannersRouteImport } from './routes/admin/banners'
import { Route as AdminAvaliacoesRouteImport } from './routes/admin/avaliacoes'
import { Route as AdminAoVivoRouteImport } from './routes/admin/ao-vivo'
import { Route as StorePerfilRouteImport } from './routes/_store.perfil'
import { Route as StorePedidosRouteImport } from './routes/_store.pedidos'
import { Route as StoreMapaSiteRouteImport } from './routes/_store.mapa-site'
import { Route as StoreLoginRouteImport } from './routes/_store.login'
import { Route as StoreFaqRouteImport } from './routes/_store.faq'
import { Route as StoreCompartilhadoRouteImport } from './routes/_store.compartilhado'
import { Route as StoreCheckoutRouteImport } from './routes/_store.checkout'
import { Route as StoreCartRouteImport } from './routes/_store.cart'
import { Route as StoreCadastroRouteImport } from './routes/_store.cadastro'
import { Route as StoreBuscaRouteImport } from './routes/_store/busca'
import { Route as StoreStoreSlugRouteImport } from './routes/_store.$storeSlug'
import { Route as AdminPedidosIndexRouteImport } from './routes/admin/pedidos/index'
import { Route as AdminLojasIndexRouteImport } from './routes/admin/lojas.index'
import { Route as AdminDesignIndexRouteImport } from './routes/admin/design.index'
import { Route as AdminConfiguracoesIndexRouteImport } from './routes/admin/configuracoes.index'
import { Route as AdminClientesIndexRouteImport } from './routes/admin/clientes/index'
import { Route as AdminVariacoesNovaRouteImport } from './routes/admin/variacoes.nova'
import { Route as AdminSolucoesAplicativosRouteImport } from './routes/admin/solucoes.aplicativos'
import { Route as AdminSelosNovoRouteImport } from './routes/admin/selos.novo'
import { Route as AdminProdutosPrecosRouteImport } from './routes/admin/produtos.precos'
import { Route as AdminProdutosNovoRouteImport } from './routes/admin/produtos.novo'
import { Route as AdminProdutosEstoqueRouteImport } from './routes/admin/produtos.estoque'
import { Route as AdminProdutosApiConexoesRouteImport } from './routes/admin/produtos.api-conexoes'
import { Route as AdminPedidosNovoRouteImport } from './routes/admin/pedidos/novo'
import { Route as AdminMarketingOrderBumpsRouteImport } from './routes/admin/marketing.order-bumps'
import { Route as AdminMarketingCompreJuntoRouteImport } from './routes/admin/marketing.compre-junto'
import { Route as AdminMarcasNovaRouteImport } from './routes/admin/marcas.nova'
import { Route as AdminLojasTabelasPrecosRouteImport } from './routes/admin/lojas.tabelas-precos'
import { Route as AdminLojasPaineisRouteImport } from './routes/admin/lojas.paineis'
import { Route as AdminLojasNovaRouteImport } from './routes/admin/lojas.nova'
import { Route as AdminLojasLinkInscricaoRouteImport } from './routes/admin/lojas.link-inscricao'
import { Route as AdminLojasGerarRouteImport } from './routes/admin/lojas.gerar'
import { Route as AdminIntegracoesWebhooksRouteImport } from './routes/admin/integracoes.webhooks'
import { Route as AdminIntegracoesCofreRouteImport } from './routes/admin/integracoes.cofre'
import { Route as AdminIntegracoesApiRouteImport } from './routes/admin/integracoes.api'
import { Route as AdminDesignVisualRouteImport } from './routes/admin/design.visual'
import { Route as AdminDesignScriptsRouteImport } from './routes/admin/design.scripts'
import { Route as AdminDesignPaginasRouteImport } from './routes/admin/design.paginas'
import { Route as AdminDesignLogoRouteImport } from './routes/admin/design.logo'
import { Route as AdminDesignCoresRouteImport } from './routes/admin/design.cores'
import { Route as AdminConfiguracoesRedirectsRouteImport } from './routes/admin/configuracoes.redirects'
import { Route as AdminConfiguracoesPagamentoRouteImport } from './routes/admin/configuracoes.pagamento'
import { Route as AdminConfiguracoesLojaRouteImport } from './routes/admin/configuracoes.loja'
import { Route as AdminConfiguracoesDominiosRouteImport } from './routes/admin/configuracoes.dominios'
import { Route as AdminCanaisIfoodRouteImport } from './routes/admin/canais.ifood'
import { Route as AdminCanaisGoogleShoppingRouteImport } from './routes/admin/canais.google-shopping'
import { Route as AdminCanaisFarmaciasappRouteImport } from './routes/admin/canais.farmaciasapp'
import { Route as StoreVSlugRouteImport } from './routes/_store/v/$slug'
import { Route as StorePaginaSlugRouteImport } from './routes/_store.pagina.$slug'
import { Route as StorePSlugRouteImport } from './routes/_store/p/$slug'
import { Route as StoreMSlugRouteImport } from './routes/_store/m/$slug'
import { Route as StoreCSlugRouteImport } from './routes/_store/c/$slug'
import { Route as StoreAjudaPageRouteImport } from './routes/_store.ajuda.$page'
import { Route as AdminMarketingPromocoesIndexRouteImport } from './routes/admin/marketing.promocoes.index'
import { Route as AdminMarketingCuponsIndexRouteImport } from './routes/admin/marketing.cupons.index'
import { Route as AdminMarketingPromocoesNovaRouteImport } from './routes/admin/marketing.promocoes.nova'
import { Route as AdminMarketingCuponsNovoRouteImport } from './routes/admin/marketing.cupons.novo'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/_store',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PainelLojaOldRoute = PainelLojaOldRouteImport.update({
  id: '/painel-loja/old',
  path: '/painel-loja/old',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelLojaLojaIdRoute = PainelLojaLojaIdRouteImport.update({
  id: '/painel-loja/$lojaId',
  path: '/painel-loja/$lojaId',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricaoTokenRoute = InscricaoTokenRouteImport.update({
  id: '/inscricao/$token',
  path: '/inscricao/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVariacoesRoute = AdminVariacoesRouteImport.update({
  id: '/variacoes',
  path: '/variacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSelosRoute = AdminSelosRouteImport.update({
  id: '/selos',
  path: '/selos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerguntasRoute = AdminPerguntasRouteImport.update({
  id: '/perguntas',
  path: '/perguntas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPbmsRoute = AdminPbmsRouteImport.update({
  id: '/pbms',
  path: '/pbms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaginasInformativasRoute =
  AdminPaginasInformativasRouteImport.update({
    id: '/paginas-informativas',
    path: '/paginas-informativas',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminMinhaLogisticaRoute = AdminMinhaLogisticaRouteImport.update({
  id: '/minha-logistica',
  path: '/minha-logistica',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMetricasRoute = AdminMetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarcasRoute = AdminMarcasRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogisticaRoute = AdminLogisticaRouteImport.update({
  id: '/logistica',
  path: '/logistica',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListaEsperaRoute = AdminListaEsperaRouteImport.update({
  id: '/lista-espera',
  path: '/lista-espera',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLinksCarrinhoRoute = AdminLinksCarrinhoRouteImport.update({
  id: '/links-carrinho',
  path: '/links-carrinho',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegracoesRoute = AdminIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFiltrosRoute = AdminFiltrosRouteImport.update({
  id: '/filtros',
  path: '/filtros',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstoqueRoute = AdminEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDescontosRoute = AdminDescontosRouteImport.update({
  id: '/descontos',
  path: '/descontos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminColecoesRoute = AdminColecoesRouteImport.update({
  id: '/colecoes',
  path: '/colecoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCarrinhosAbandonadosRoute =
  AdminCarrinhosAbandonadosRouteImport.update({
    id: '/carrinhos-abandonados',
    path: '/carrinhos-abandonados',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAvaliacoesRoute = AdminAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAoVivoRoute = AdminAoVivoRouteImport.update({
  id: '/ao-vivo',
  path: '/ao-vivo',
  getParentRoute: () => AdminRoute,
} as any)
const StorePerfilRoute = StorePerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => StoreRoute,
} as any)
const StorePedidosRoute = StorePedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => StoreRoute,
} as any)
const StoreMapaSiteRoute = StoreMapaSiteRouteImport.update({
  id: '/mapa-site',
  path: '/mapa-site',
  getParentRoute: () => StoreRoute,
} as any)
const StoreLoginRoute = StoreLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => StoreRoute,
} as any)
const StoreFaqRoute = StoreFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCompartilhadoRoute = StoreCompartilhadoRouteImport.update({
  id: '/compartilhado',
  path: '/compartilhado',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCheckoutRoute = StoreCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCartRoute = StoreCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCadastroRoute = StoreCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => StoreRoute,
} as any)
const StoreBuscaRoute = StoreBuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => StoreRoute,
} as any)
const StoreStoreSlugRoute = StoreStoreSlugRouteImport.update({
  id: '/$storeSlug',
  path: '/$storeSlug',
  getParentRoute: () => StoreRoute,
} as any)
const AdminPedidosIndexRoute = AdminPedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLojasIndexRoute = AdminLojasIndexRouteImport.update({
  id: '/lojas/',
  path: '/lojas/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDesignIndexRoute = AdminDesignIndexRouteImport.update({
  id: '/design/',
  path: '/design/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesIndexRoute = AdminConfiguracoesIndexRouteImport.update({
  id: '/configuracoes/',
  path: '/configuracoes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesIndexRoute = AdminClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVariacoesNovaRoute = AdminVariacoesNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AdminVariacoesRoute,
} as any)
const AdminSolucoesAplicativosRoute =
  AdminSolucoesAplicativosRouteImport.update({
    id: '/solucoes/aplicativos',
    path: '/solucoes/aplicativos',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSelosNovoRoute = AdminSelosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AdminSelosRoute,
} as any)
const AdminProdutosPrecosRoute = AdminProdutosPrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => AdminProdutosRoute,
} as any)
const AdminProdutosNovoRoute = AdminProdutosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AdminProdutosRoute,
} as any)
const AdminProdutosEstoqueRoute = AdminProdutosEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AdminProdutosRoute,
} as any)
const AdminProdutosApiConexoesRoute =
  AdminProdutosApiConexoesRouteImport.update({
    id: '/api-conexoes',
    path: '/api-conexoes',
    getParentRoute: () => AdminProdutosRoute,
  } as any)
const AdminPedidosNovoRoute = AdminPedidosNovoRouteImport.update({
  id: '/pedidos/novo',
  path: '/pedidos/novo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingOrderBumpsRoute =
  AdminMarketingOrderBumpsRouteImport.update({
    id: '/marketing/order-bumps',
    path: '/marketing/order-bumps',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminMarketingCompreJuntoRoute =
  AdminMarketingCompreJuntoRouteImport.update({
    id: '/marketing/compre-junto',
    path: '/marketing/compre-junto',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminMarcasNovaRoute = AdminMarcasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AdminMarcasRoute,
} as any)
const AdminLojasTabelasPrecosRoute = AdminLojasTabelasPrecosRouteImport.update({
  id: '/lojas/tabelas-precos',
  path: '/lojas/tabelas-precos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLojasPaineisRoute = AdminLojasPaineisRouteImport.update({
  id: '/lojas/paineis',
  path: '/lojas/paineis',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLojasNovaRoute = AdminLojasNovaRouteImport.update({
  id: '/lojas/nova',
  path: '/lojas/nova',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLojasLinkInscricaoRoute = AdminLojasLinkInscricaoRouteImport.update({
  id: '/lojas/link-inscricao',
  path: '/lojas/link-inscricao',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLojasGerarRoute = AdminLojasGerarRouteImport.update({
  id: '/lojas/gerar',
  path: '/lojas/gerar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegracoesWebhooksRoute =
  AdminIntegracoesWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AdminIntegracoesRoute,
  } as any)
const AdminIntegracoesCofreRoute = AdminIntegracoesCofreRouteImport.update({
  id: '/cofre',
  path: '/cofre',
  getParentRoute: () => AdminIntegracoesRoute,
} as any)
const AdminIntegracoesApiRoute = AdminIntegracoesApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AdminIntegracoesRoute,
} as any)
const AdminDesignVisualRoute = AdminDesignVisualRouteImport.update({
  id: '/design/visual',
  path: '/design/visual',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDesignScriptsRoute = AdminDesignScriptsRouteImport.update({
  id: '/design/scripts',
  path: '/design/scripts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDesignPaginasRoute = AdminDesignPaginasRouteImport.update({
  id: '/design/paginas',
  path: '/design/paginas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDesignLogoRoute = AdminDesignLogoRouteImport.update({
  id: '/design/logo',
  path: '/design/logo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDesignCoresRoute = AdminDesignCoresRouteImport.update({
  id: '/design/cores',
  path: '/design/cores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRedirectsRoute =
  AdminConfiguracoesRedirectsRouteImport.update({
    id: '/configuracoes/redirects',
    path: '/configuracoes/redirects',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminConfiguracoesPagamentoRoute =
  AdminConfiguracoesPagamentoRouteImport.update({
    id: '/configuracoes/pagamento',
    path: '/configuracoes/pagamento',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminConfiguracoesLojaRoute = AdminConfiguracoesLojaRouteImport.update({
  id: '/configuracoes/loja',
  path: '/configuracoes/loja',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesDominiosRoute =
  AdminConfiguracoesDominiosRouteImport.update({
    id: '/configuracoes/dominios',
    path: '/configuracoes/dominios',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCanaisIfoodRoute = AdminCanaisIfoodRouteImport.update({
  id: '/canais/ifood',
  path: '/canais/ifood',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCanaisGoogleShoppingRoute =
  AdminCanaisGoogleShoppingRouteImport.update({
    id: '/canais/google-shopping',
    path: '/canais/google-shopping',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCanaisFarmaciasappRoute = AdminCanaisFarmaciasappRouteImport.update({
  id: '/canais/farmaciasapp',
  path: '/canais/farmaciasapp',
  getParentRoute: () => AdminRoute,
} as any)
const StoreVSlugRoute = StoreVSlugRouteImport.update({
  id: '/v/$slug',
  path: '/v/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const StorePaginaSlugRoute = StorePaginaSlugRouteImport.update({
  id: '/pagina/$slug',
  path: '/pagina/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const StorePSlugRoute = StorePSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const StoreMSlugRoute = StoreMSlugRouteImport.update({
  id: '/m/$slug',
  path: '/m/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCSlugRoute = StoreCSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const StoreAjudaPageRoute = StoreAjudaPageRouteImport.update({
  id: '/ajuda/$page',
  path: '/ajuda/$page',
  getParentRoute: () => StoreRoute,
} as any)
const AdminMarketingPromocoesIndexRoute =
  AdminMarketingPromocoesIndexRouteImport.update({
    id: '/marketing/promocoes/',
    path: '/marketing/promocoes/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminMarketingCuponsIndexRoute =
  AdminMarketingCuponsIndexRouteImport.update({
    id: '/marketing/cupons/',
    path: '/marketing/cupons/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminMarketingPromocoesNovaRoute =
  AdminMarketingPromocoesNovaRouteImport.update({
    id: '/marketing/promocoes/nova',
    path: '/marketing/promocoes/nova',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminMarketingCuponsNovoRoute =
  AdminMarketingCuponsNovoRouteImport.update({
    id: '/marketing/cupons/novo',
    path: '/marketing/cupons/novo',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/$storeSlug': typeof StoreStoreSlugRoute
  '/busca': typeof StoreBuscaRoute
  '/cadastro': typeof StoreCadastroRoute
  '/cart': typeof StoreCartRoute
  '/checkout': typeof StoreCheckoutRoute
  '/compartilhado': typeof StoreCompartilhadoRoute
  '/faq': typeof StoreFaqRoute
  '/login': typeof StoreLoginRoute
  '/mapa-site': typeof StoreMapaSiteRoute
  '/pedidos': typeof StorePedidosRoute
  '/perfil': typeof StorePerfilRoute
  '/admin/ao-vivo': typeof AdminAoVivoRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/carrinhos-abandonados': typeof AdminCarrinhosAbandonadosRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/colecoes': typeof AdminColecoesRoute
  '/admin/descontos': typeof AdminDescontosRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/filtros': typeof AdminFiltrosRoute
  '/admin/integracoes': typeof AdminIntegracoesRouteWithChildren
  '/admin/links-carrinho': typeof AdminLinksCarrinhoRoute
  '/admin/lista-espera': typeof AdminListaEsperaRoute
  '/admin/logistica': typeof AdminLogisticaRoute
  '/admin/marcas': typeof AdminMarcasRouteWithChildren
  '/admin/metricas': typeof AdminMetricasRoute
  '/admin/minha-logistica': typeof AdminMinhaLogisticaRoute
  '/admin/paginas-informativas': typeof AdminPaginasInformativasRoute
  '/admin/pbms': typeof AdminPbmsRoute
  '/admin/perguntas': typeof AdminPerguntasRoute
  '/admin/produtos': typeof AdminProdutosRouteWithChildren
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/selos': typeof AdminSelosRouteWithChildren
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/variacoes': typeof AdminVariacoesRouteWithChildren
  '/inscricao/$token': typeof InscricaoTokenRoute
  '/painel-loja/$lojaId': typeof PainelLojaLojaIdRoute
  '/painel-loja/old': typeof PainelLojaOldRoute
  '/admin/': typeof AdminIndexRoute
  '/ajuda/$page': typeof StoreAjudaPageRoute
  '/c/$slug': typeof StoreCSlugRoute
  '/m/$slug': typeof StoreMSlugRoute
  '/p/$slug': typeof StorePSlugRoute
  '/pagina/$slug': typeof StorePaginaSlugRoute
  '/v/$slug': typeof StoreVSlugRoute
  '/admin/canais/farmaciasapp': typeof AdminCanaisFarmaciasappRoute
  '/admin/canais/google-shopping': typeof AdminCanaisGoogleShoppingRoute
  '/admin/canais/ifood': typeof AdminCanaisIfoodRoute
  '/admin/configuracoes/dominios': typeof AdminConfiguracoesDominiosRoute
  '/admin/configuracoes/loja': typeof AdminConfiguracoesLojaRoute
  '/admin/configuracoes/pagamento': typeof AdminConfiguracoesPagamentoRoute
  '/admin/configuracoes/redirects': typeof AdminConfiguracoesRedirectsRoute
  '/admin/design/cores': typeof AdminDesignCoresRoute
  '/admin/design/logo': typeof AdminDesignLogoRoute
  '/admin/design/paginas': typeof AdminDesignPaginasRoute
  '/admin/design/scripts': typeof AdminDesignScriptsRoute
  '/admin/design/visual': typeof AdminDesignVisualRoute
  '/admin/integracoes/api': typeof AdminIntegracoesApiRoute
  '/admin/integracoes/cofre': typeof AdminIntegracoesCofreRoute
  '/admin/integracoes/webhooks': typeof AdminIntegracoesWebhooksRoute
  '/admin/lojas/gerar': typeof AdminLojasGerarRoute
  '/admin/lojas/link-inscricao': typeof AdminLojasLinkInscricaoRoute
  '/admin/lojas/nova': typeof AdminLojasNovaRoute
  '/admin/lojas/paineis': typeof AdminLojasPaineisRoute
  '/admin/lojas/tabelas-precos': typeof AdminLojasTabelasPrecosRoute
  '/admin/marcas/nova': typeof AdminMarcasNovaRoute
  '/admin/marketing/compre-junto': typeof AdminMarketingCompreJuntoRoute
  '/admin/marketing/order-bumps': typeof AdminMarketingOrderBumpsRoute
  '/admin/pedidos/novo': typeof AdminPedidosNovoRoute
  '/admin/produtos/api-conexoes': typeof AdminProdutosApiConexoesRoute
  '/admin/produtos/estoque': typeof AdminProdutosEstoqueRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/admin/produtos/precos': typeof AdminProdutosPrecosRoute
  '/admin/selos/novo': typeof AdminSelosNovoRoute
  '/admin/solucoes/aplicativos': typeof AdminSolucoesAplicativosRoute
  '/admin/variacoes/nova': typeof AdminVariacoesNovaRoute
  '/admin/clientes/': typeof AdminClientesIndexRoute
  '/admin/configuracoes/': typeof AdminConfiguracoesIndexRoute
  '/admin/design/': typeof AdminDesignIndexRoute
  '/admin/lojas/': typeof AdminLojasIndexRoute
  '/admin/pedidos/': typeof AdminPedidosIndexRoute
  '/admin/marketing/cupons/novo': typeof AdminMarketingCuponsNovoRoute
  '/admin/marketing/promocoes/nova': typeof AdminMarketingPromocoesNovaRoute
  '/admin/marketing/cupons/': typeof AdminMarketingCuponsIndexRoute
  '/admin/marketing/promocoes/': typeof AdminMarketingPromocoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$storeSlug': typeof StoreStoreSlugRoute
  '/busca': typeof StoreBuscaRoute
  '/cadastro': typeof StoreCadastroRoute
  '/cart': typeof StoreCartRoute
  '/checkout': typeof StoreCheckoutRoute
  '/compartilhado': typeof StoreCompartilhadoRoute
  '/faq': typeof StoreFaqRoute
  '/login': typeof StoreLoginRoute
  '/mapa-site': typeof StoreMapaSiteRoute
  '/pedidos': typeof StorePedidosRoute
  '/perfil': typeof StorePerfilRoute
  '/admin/ao-vivo': typeof AdminAoVivoRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/carrinhos-abandonados': typeof AdminCarrinhosAbandonadosRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/colecoes': typeof AdminColecoesRoute
  '/admin/descontos': typeof AdminDescontosRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/filtros': typeof AdminFiltrosRoute
  '/admin/integracoes': typeof AdminIntegracoesRouteWithChildren
  '/admin/links-carrinho': typeof AdminLinksCarrinhoRoute
  '/admin/lista-espera': typeof AdminListaEsperaRoute
  '/admin/logistica': typeof AdminLogisticaRoute
  '/admin/marcas': typeof AdminMarcasRouteWithChildren
  '/admin/metricas': typeof AdminMetricasRoute
  '/admin/minha-logistica': typeof AdminMinhaLogisticaRoute
  '/admin/paginas-informativas': typeof AdminPaginasInformativasRoute
  '/admin/pbms': typeof AdminPbmsRoute
  '/admin/perguntas': typeof AdminPerguntasRoute
  '/admin/produtos': typeof AdminProdutosRouteWithChildren
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/selos': typeof AdminSelosRouteWithChildren
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/variacoes': typeof AdminVariacoesRouteWithChildren
  '/inscricao/$token': typeof InscricaoTokenRoute
  '/painel-loja/$lojaId': typeof PainelLojaLojaIdRoute
  '/painel-loja/old': typeof PainelLojaOldRoute
  '/admin': typeof AdminIndexRoute
  '/ajuda/$page': typeof StoreAjudaPageRoute
  '/c/$slug': typeof StoreCSlugRoute
  '/m/$slug': typeof StoreMSlugRoute
  '/p/$slug': typeof StorePSlugRoute
  '/pagina/$slug': typeof StorePaginaSlugRoute
  '/v/$slug': typeof StoreVSlugRoute
  '/admin/canais/farmaciasapp': typeof AdminCanaisFarmaciasappRoute
  '/admin/canais/google-shopping': typeof AdminCanaisGoogleShoppingRoute
  '/admin/canais/ifood': typeof AdminCanaisIfoodRoute
  '/admin/configuracoes/dominios': typeof AdminConfiguracoesDominiosRoute
  '/admin/configuracoes/loja': typeof AdminConfiguracoesLojaRoute
  '/admin/configuracoes/pagamento': typeof AdminConfiguracoesPagamentoRoute
  '/admin/configuracoes/redirects': typeof AdminConfiguracoesRedirectsRoute
  '/admin/design/cores': typeof AdminDesignCoresRoute
  '/admin/design/logo': typeof AdminDesignLogoRoute
  '/admin/design/paginas': typeof AdminDesignPaginasRoute
  '/admin/design/scripts': typeof AdminDesignScriptsRoute
  '/admin/design/visual': typeof AdminDesignVisualRoute
  '/admin/integracoes/api': typeof AdminIntegracoesApiRoute
  '/admin/integracoes/cofre': typeof AdminIntegracoesCofreRoute
  '/admin/integracoes/webhooks': typeof AdminIntegracoesWebhooksRoute
  '/admin/lojas/gerar': typeof AdminLojasGerarRoute
  '/admin/lojas/link-inscricao': typeof AdminLojasLinkInscricaoRoute
  '/admin/lojas/nova': typeof AdminLojasNovaRoute
  '/admin/lojas/paineis': typeof AdminLojasPaineisRoute
  '/admin/lojas/tabelas-precos': typeof AdminLojasTabelasPrecosRoute
  '/admin/marcas/nova': typeof AdminMarcasNovaRoute
  '/admin/marketing/compre-junto': typeof AdminMarketingCompreJuntoRoute
  '/admin/marketing/order-bumps': typeof AdminMarketingOrderBumpsRoute
  '/admin/pedidos/novo': typeof AdminPedidosNovoRoute
  '/admin/produtos/api-conexoes': typeof AdminProdutosApiConexoesRoute
  '/admin/produtos/estoque': typeof AdminProdutosEstoqueRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/admin/produtos/precos': typeof AdminProdutosPrecosRoute
  '/admin/selos/novo': typeof AdminSelosNovoRoute
  '/admin/solucoes/aplicativos': typeof AdminSolucoesAplicativosRoute
  '/admin/variacoes/nova': typeof AdminVariacoesNovaRoute
  '/admin/clientes': typeof AdminClientesIndexRoute
  '/admin/configuracoes': typeof AdminConfiguracoesIndexRoute
  '/admin/design': typeof AdminDesignIndexRoute
  '/admin/lojas': typeof AdminLojasIndexRoute
  '/admin/pedidos': typeof AdminPedidosIndexRoute
  '/admin/marketing/cupons/novo': typeof AdminMarketingCuponsNovoRoute
  '/admin/marketing/promocoes/nova': typeof AdminMarketingPromocoesNovaRoute
  '/admin/marketing/cupons': typeof AdminMarketingCuponsIndexRoute
  '/admin/marketing/promocoes': typeof AdminMarketingPromocoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_store': typeof StoreRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_store/$storeSlug': typeof StoreStoreSlugRoute
  '/_store/busca': typeof StoreBuscaRoute
  '/_store/cadastro': typeof StoreCadastroRoute
  '/_store/cart': typeof StoreCartRoute
  '/_store/checkout': typeof StoreCheckoutRoute
  '/_store/compartilhado': typeof StoreCompartilhadoRoute
  '/_store/faq': typeof StoreFaqRoute
  '/_store/login': typeof StoreLoginRoute
  '/_store/mapa-site': typeof StoreMapaSiteRoute
  '/_store/pedidos': typeof StorePedidosRoute
  '/_store/perfil': typeof StorePerfilRoute
  '/admin/ao-vivo': typeof AdminAoVivoRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/carrinhos-abandonados': typeof AdminCarrinhosAbandonadosRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/colecoes': typeof AdminColecoesRoute
  '/admin/descontos': typeof AdminDescontosRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/filtros': typeof AdminFiltrosRoute
  '/admin/integracoes': typeof AdminIntegracoesRouteWithChildren
  '/admin/links-carrinho': typeof AdminLinksCarrinhoRoute
  '/admin/lista-espera': typeof AdminListaEsperaRoute
  '/admin/logistica': typeof AdminLogisticaRoute
  '/admin/marcas': typeof AdminMarcasRouteWithChildren
  '/admin/metricas': typeof AdminMetricasRoute
  '/admin/minha-logistica': typeof AdminMinhaLogisticaRoute
  '/admin/paginas-informativas': typeof AdminPaginasInformativasRoute
  '/admin/pbms': typeof AdminPbmsRoute
  '/admin/perguntas': typeof AdminPerguntasRoute
  '/admin/produtos': typeof AdminProdutosRouteWithChildren
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/selos': typeof AdminSelosRouteWithChildren
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/variacoes': typeof AdminVariacoesRouteWithChildren
  '/inscricao/$token': typeof InscricaoTokenRoute
  '/painel-loja/$lojaId': typeof PainelLojaLojaIdRoute
  '/painel-loja/old': typeof PainelLojaOldRoute
  '/admin/': typeof AdminIndexRoute
  '/_store/ajuda/$page': typeof StoreAjudaPageRoute
  '/_store/c/$slug': typeof StoreCSlugRoute
  '/_store/m/$slug': typeof StoreMSlugRoute
  '/_store/p/$slug': typeof StorePSlugRoute
  '/_store/pagina/$slug': typeof StorePaginaSlugRoute
  '/_store/v/$slug': typeof StoreVSlugRoute
  '/admin/canais/farmaciasapp': typeof AdminCanaisFarmaciasappRoute
  '/admin/canais/google-shopping': typeof AdminCanaisGoogleShoppingRoute
  '/admin/canais/ifood': typeof AdminCanaisIfoodRoute
  '/admin/configuracoes/dominios': typeof AdminConfiguracoesDominiosRoute
  '/admin/configuracoes/loja': typeof AdminConfiguracoesLojaRoute
  '/admin/configuracoes/pagamento': typeof AdminConfiguracoesPagamentoRoute
  '/admin/configuracoes/redirects': typeof AdminConfiguracoesRedirectsRoute
  '/admin/design/cores': typeof AdminDesignCoresRoute
  '/admin/design/logo': typeof AdminDesignLogoRoute
  '/admin/design/paginas': typeof AdminDesignPaginasRoute
  '/admin/design/scripts': typeof AdminDesignScriptsRoute
  '/admin/design/visual': typeof AdminDesignVisualRoute
  '/admin/integracoes/api': typeof AdminIntegracoesApiRoute
  '/admin/integracoes/cofre': typeof AdminIntegracoesCofreRoute
  '/admin/integracoes/webhooks': typeof AdminIntegracoesWebhooksRoute
  '/admin/lojas/gerar': typeof AdminLojasGerarRoute
  '/admin/lojas/link-inscricao': typeof AdminLojasLinkInscricaoRoute
  '/admin/lojas/nova': typeof AdminLojasNovaRoute
  '/admin/lojas/paineis': typeof AdminLojasPaineisRoute
  '/admin/lojas/tabelas-precos': typeof AdminLojasTabelasPrecosRoute
  '/admin/marcas/nova': typeof AdminMarcasNovaRoute
  '/admin/marketing/compre-junto': typeof AdminMarketingCompreJuntoRoute
  '/admin/marketing/order-bumps': typeof AdminMarketingOrderBumpsRoute
  '/admin/pedidos/novo': typeof AdminPedidosNovoRoute
  '/admin/produtos/api-conexoes': typeof AdminProdutosApiConexoesRoute
  '/admin/produtos/estoque': typeof AdminProdutosEstoqueRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/admin/produtos/precos': typeof AdminProdutosPrecosRoute
  '/admin/selos/novo': typeof AdminSelosNovoRoute
  '/admin/solucoes/aplicativos': typeof AdminSolucoesAplicativosRoute
  '/admin/variacoes/nova': typeof AdminVariacoesNovaRoute
  '/admin/clientes/': typeof AdminClientesIndexRoute
  '/admin/configuracoes/': typeof AdminConfiguracoesIndexRoute
  '/admin/design/': typeof AdminDesignIndexRoute
  '/admin/lojas/': typeof AdminLojasIndexRoute
  '/admin/pedidos/': typeof AdminPedidosIndexRoute
  '/admin/marketing/cupons/novo': typeof AdminMarketingCuponsNovoRoute
  '/admin/marketing/promocoes/nova': typeof AdminMarketingPromocoesNovaRoute
  '/admin/marketing/cupons/': typeof AdminMarketingCuponsIndexRoute
  '/admin/marketing/promocoes/': typeof AdminMarketingPromocoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/$storeSlug'
    | '/busca'
    | '/cadastro'
    | '/cart'
    | '/checkout'
    | '/compartilhado'
    | '/faq'
    | '/login'
    | '/mapa-site'
    | '/pedidos'
    | '/perfil'
    | '/admin/ao-vivo'
    | '/admin/avaliacoes'
    | '/admin/banners'
    | '/admin/carrinhos-abandonados'
    | '/admin/categorias'
    | '/admin/colecoes'
    | '/admin/descontos'
    | '/admin/estoque'
    | '/admin/filtros'
    | '/admin/integracoes'
    | '/admin/links-carrinho'
    | '/admin/lista-espera'
    | '/admin/logistica'
    | '/admin/marcas'
    | '/admin/metricas'
    | '/admin/minha-logistica'
    | '/admin/paginas-informativas'
    | '/admin/pbms'
    | '/admin/perguntas'
    | '/admin/produtos'
    | '/admin/relatorios'
    | '/admin/selos'
    | '/admin/usuarios'
    | '/admin/variacoes'
    | '/inscricao/$token'
    | '/painel-loja/$lojaId'
    | '/painel-loja/old'
    | '/admin/'
    | '/ajuda/$page'
    | '/c/$slug'
    | '/m/$slug'
    | '/p/$slug'
    | '/pagina/$slug'
    | '/v/$slug'
    | '/admin/canais/farmaciasapp'
    | '/admin/canais/google-shopping'
    | '/admin/canais/ifood'
    | '/admin/configuracoes/dominios'
    | '/admin/configuracoes/loja'
    | '/admin/configuracoes/pagamento'
    | '/admin/configuracoes/redirects'
    | '/admin/design/cores'
    | '/admin/design/logo'
    | '/admin/design/paginas'
    | '/admin/design/scripts'
    | '/admin/design/visual'
    | '/admin/integracoes/api'
    | '/admin/integracoes/cofre'
    | '/admin/integracoes/webhooks'
    | '/admin/lojas/gerar'
    | '/admin/lojas/link-inscricao'
    | '/admin/lojas/nova'
    | '/admin/lojas/paineis'
    | '/admin/lojas/tabelas-precos'
    | '/admin/marcas/nova'
    | '/admin/marketing/compre-junto'
    | '/admin/marketing/order-bumps'
    | '/admin/pedidos/novo'
    | '/admin/produtos/api-conexoes'
    | '/admin/produtos/estoque'
    | '/admin/produtos/novo'
    | '/admin/produtos/precos'
    | '/admin/selos/novo'
    | '/admin/solucoes/aplicativos'
    | '/admin/variacoes/nova'
    | '/admin/clientes/'
    | '/admin/configuracoes/'
    | '/admin/design/'
    | '/admin/lojas/'
    | '/admin/pedidos/'
    | '/admin/marketing/cupons/novo'
    | '/admin/marketing/promocoes/nova'
    | '/admin/marketing/cupons/'
    | '/admin/marketing/promocoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$storeSlug'
    | '/busca'
    | '/cadastro'
    | '/cart'
    | '/checkout'
    | '/compartilhado'
    | '/faq'
    | '/login'
    | '/mapa-site'
    | '/pedidos'
    | '/perfil'
    | '/admin/ao-vivo'
    | '/admin/avaliacoes'
    | '/admin/banners'
    | '/admin/carrinhos-abandonados'
    | '/admin/categorias'
    | '/admin/colecoes'
    | '/admin/descontos'
    | '/admin/estoque'
    | '/admin/filtros'
    | '/admin/integracoes'
    | '/admin/links-carrinho'
    | '/admin/lista-espera'
    | '/admin/logistica'
    | '/admin/marcas'
    | '/admin/metricas'
    | '/admin/minha-logistica'
    | '/admin/paginas-informativas'
    | '/admin/pbms'
    | '/admin/perguntas'
    | '/admin/produtos'
    | '/admin/relatorios'
    | '/admin/selos'
    | '/admin/usuarios'
    | '/admin/variacoes'
    | '/inscricao/$token'
    | '/painel-loja/$lojaId'
    | '/painel-loja/old'
    | '/admin'
    | '/ajuda/$page'
    | '/c/$slug'
    | '/m/$slug'
    | '/p/$slug'
    | '/pagina/$slug'
    | '/v/$slug'
    | '/admin/canais/farmaciasapp'
    | '/admin/canais/google-shopping'
    | '/admin/canais/ifood'
    | '/admin/configuracoes/dominios'
    | '/admin/configuracoes/loja'
    | '/admin/configuracoes/pagamento'
    | '/admin/configuracoes/redirects'
    | '/admin/design/cores'
    | '/admin/design/logo'
    | '/admin/design/paginas'
    | '/admin/design/scripts'
    | '/admin/design/visual'
    | '/admin/integracoes/api'
    | '/admin/integracoes/cofre'
    | '/admin/integracoes/webhooks'
    | '/admin/lojas/gerar'
    | '/admin/lojas/link-inscricao'
    | '/admin/lojas/nova'
    | '/admin/lojas/paineis'
    | '/admin/lojas/tabelas-precos'
    | '/admin/marcas/nova'
    | '/admin/marketing/compre-junto'
    | '/admin/marketing/order-bumps'
    | '/admin/pedidos/novo'
    | '/admin/produtos/api-conexoes'
    | '/admin/produtos/estoque'
    | '/admin/produtos/novo'
    | '/admin/produtos/precos'
    | '/admin/selos/novo'
    | '/admin/solucoes/aplicativos'
    | '/admin/variacoes/nova'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/design'
    | '/admin/lojas'
    | '/admin/pedidos'
    | '/admin/marketing/cupons/novo'
    | '/admin/marketing/promocoes/nova'
    | '/admin/marketing/cupons'
    | '/admin/marketing/promocoes'
  id:
    | '__root__'
    | '/'
    | '/_store'
    | '/admin'
    | '/_store/$storeSlug'
    | '/_store/busca'
    | '/_store/cadastro'
    | '/_store/cart'
    | '/_store/checkout'
    | '/_store/compartilhado'
    | '/_store/faq'
    | '/_store/login'
    | '/_store/mapa-site'
    | '/_store/pedidos'
    | '/_store/perfil'
    | '/admin/ao-vivo'
    | '/admin/avaliacoes'
    | '/admin/banners'
    | '/admin/carrinhos-abandonados'
    | '/admin/categorias'
    | '/admin/colecoes'
    | '/admin/descontos'
    | '/admin/estoque'
    | '/admin/filtros'
    | '/admin/integracoes'
    | '/admin/links-carrinho'
    | '/admin/lista-espera'
    | '/admin/logistica'
    | '/admin/marcas'
    | '/admin/metricas'
    | '/admin/minha-logistica'
    | '/admin/paginas-informativas'
    | '/admin/pbms'
    | '/admin/perguntas'
    | '/admin/produtos'
    | '/admin/relatorios'
    | '/admin/selos'
    | '/admin/usuarios'
    | '/admin/variacoes'
    | '/inscricao/$token'
    | '/painel-loja/$lojaId'
    | '/painel-loja/old'
    | '/admin/'
    | '/_store/ajuda/$page'
    | '/_store/c/$slug'
    | '/_store/m/$slug'
    | '/_store/p/$slug'
    | '/_store/pagina/$slug'
    | '/_store/v/$slug'
    | '/admin/canais/farmaciasapp'
    | '/admin/canais/google-shopping'
    | '/admin/canais/ifood'
    | '/admin/configuracoes/dominios'
    | '/admin/configuracoes/loja'
    | '/admin/configuracoes/pagamento'
    | '/admin/configuracoes/redirects'
    | '/admin/design/cores'
    | '/admin/design/logo'
    | '/admin/design/paginas'
    | '/admin/design/scripts'
    | '/admin/design/visual'
    | '/admin/integracoes/api'
    | '/admin/integracoes/cofre'
    | '/admin/integracoes/webhooks'
    | '/admin/lojas/gerar'
    | '/admin/lojas/link-inscricao'
    | '/admin/lojas/nova'
    | '/admin/lojas/paineis'
    | '/admin/lojas/tabelas-precos'
    | '/admin/marcas/nova'
    | '/admin/marketing/compre-junto'
    | '/admin/marketing/order-bumps'
    | '/admin/pedidos/novo'
    | '/admin/produtos/api-conexoes'
    | '/admin/produtos/estoque'
    | '/admin/produtos/novo'
    | '/admin/produtos/precos'
    | '/admin/selos/novo'
    | '/admin/solucoes/aplicativos'
    | '/admin/variacoes/nova'
    | '/admin/clientes/'
    | '/admin/configuracoes/'
    | '/admin/design/'
    | '/admin/lojas/'
    | '/admin/pedidos/'
    | '/admin/marketing/cupons/novo'
    | '/admin/marketing/promocoes/nova'
    | '/admin/marketing/cupons/'
    | '/admin/marketing/promocoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StoreRoute: typeof StoreRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  InscricaoTokenRoute: typeof InscricaoTokenRoute
  PainelLojaLojaIdRoute: typeof PainelLojaLojaIdRoute
  PainelLojaOldRoute: typeof PainelLojaOldRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_store': {
      id: '/_store'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/painel-loja/old': {
      id: '/painel-loja/old'
      path: '/painel-loja/old'
      fullPath: '/painel-loja/old'
      preLoaderRoute: typeof PainelLojaOldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel-loja/$lojaId': {
      id: '/painel-loja/$lojaId'
      path: '/painel-loja/$lojaId'
      fullPath: '/painel-loja/$lojaId'
      preLoaderRoute: typeof PainelLojaLojaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricao/$token': {
      id: '/inscricao/$token'
      path: '/inscricao/$token'
      fullPath: '/inscricao/$token'
      preLoaderRoute: typeof InscricaoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/variacoes': {
      id: '/admin/variacoes'
      path: '/variacoes'
      fullPath: '/admin/variacoes'
      preLoaderRoute: typeof AdminVariacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/selos': {
      id: '/admin/selos'
      path: '/selos'
      fullPath: '/admin/selos'
      preLoaderRoute: typeof AdminSelosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/perguntas': {
      id: '/admin/perguntas'
      path: '/perguntas'
      fullPath: '/admin/perguntas'
      preLoaderRoute: typeof AdminPerguntasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pbms': {
      id: '/admin/pbms'
      path: '/pbms'
      fullPath: '/admin/pbms'
      preLoaderRoute: typeof AdminPbmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/paginas-informativas': {
      id: '/admin/paginas-informativas'
      path: '/paginas-informativas'
      fullPath: '/admin/paginas-informativas'
      preLoaderRoute: typeof AdminPaginasInformativasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/minha-logistica': {
      id: '/admin/minha-logistica'
      path: '/minha-logistica'
      fullPath: '/admin/minha-logistica'
      preLoaderRoute: typeof AdminMinhaLogisticaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/metricas': {
      id: '/admin/metricas'
      path: '/metricas'
      fullPath: '/admin/metricas'
      preLoaderRoute: typeof AdminMetricasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marcas': {
      id: '/admin/marcas'
      path: '/marcas'
      fullPath: '/admin/marcas'
      preLoaderRoute: typeof AdminMarcasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logistica': {
      id: '/admin/logistica'
      path: '/logistica'
      fullPath: '/admin/logistica'
      preLoaderRoute: typeof AdminLogisticaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lista-espera': {
      id: '/admin/lista-espera'
      path: '/lista-espera'
      fullPath: '/admin/lista-espera'
      preLoaderRoute: typeof AdminListaEsperaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/links-carrinho': {
      id: '/admin/links-carrinho'
      path: '/links-carrinho'
      fullPath: '/admin/links-carrinho'
      preLoaderRoute: typeof AdminLinksCarrinhoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integracoes': {
      id: '/admin/integracoes'
      path: '/integracoes'
      fullPath: '/admin/integracoes'
      preLoaderRoute: typeof AdminIntegracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/filtros': {
      id: '/admin/filtros'
      path: '/filtros'
      fullPath: '/admin/filtros'
      preLoaderRoute: typeof AdminFiltrosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estoque': {
      id: '/admin/estoque'
      path: '/estoque'
      fullPath: '/admin/estoque'
      preLoaderRoute: typeof AdminEstoqueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/descontos': {
      id: '/admin/descontos'
      path: '/descontos'
      fullPath: '/admin/descontos'
      preLoaderRoute: typeof AdminDescontosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/colecoes': {
      id: '/admin/colecoes'
      path: '/colecoes'
      fullPath: '/admin/colecoes'
      preLoaderRoute: typeof AdminColecoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/carrinhos-abandonados': {
      id: '/admin/carrinhos-abandonados'
      path: '/carrinhos-abandonados'
      fullPath: '/admin/carrinhos-abandonados'
      preLoaderRoute: typeof AdminCarrinhosAbandonadosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/avaliacoes': {
      id: '/admin/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/admin/avaliacoes'
      preLoaderRoute: typeof AdminAvaliacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ao-vivo': {
      id: '/admin/ao-vivo'
      path: '/ao-vivo'
      fullPath: '/admin/ao-vivo'
      preLoaderRoute: typeof AdminAoVivoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_store/perfil': {
      id: '/_store/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof StorePerfilRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/pedidos': {
      id: '/_store/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof StorePedidosRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/mapa-site': {
      id: '/_store/mapa-site'
      path: '/mapa-site'
      fullPath: '/mapa-site'
      preLoaderRoute: typeof StoreMapaSiteRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/login': {
      id: '/_store/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof StoreLoginRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/faq': {
      id: '/_store/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof StoreFaqRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/compartilhado': {
      id: '/_store/compartilhado'
      path: '/compartilhado'
      fullPath: '/compartilhado'
      preLoaderRoute: typeof StoreCompartilhadoRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/checkout': {
      id: '/_store/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof StoreCheckoutRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/cart': {
      id: '/_store/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof StoreCartRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/cadastro': {
      id: '/_store/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof StoreCadastroRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/busca': {
      id: '/_store/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof StoreBuscaRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/$storeSlug': {
      id: '/_store/$storeSlug'
      path: '/$storeSlug'
      fullPath: '/$storeSlug'
      preLoaderRoute: typeof StoreStoreSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/admin/pedidos/': {
      id: '/admin/pedidos/'
      path: '/pedidos'
      fullPath: '/admin/pedidos/'
      preLoaderRoute: typeof AdminPedidosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lojas/': {
      id: '/admin/lojas/'
      path: '/lojas'
      fullPath: '/admin/lojas/'
      preLoaderRoute: typeof AdminLojasIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/design/': {
      id: '/admin/design/'
      path: '/design'
      fullPath: '/admin/design/'
      preLoaderRoute: typeof AdminDesignIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes/': {
      id: '/admin/configuracoes/'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes/'
      preLoaderRoute: typeof AdminConfiguracoesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes/': {
      id: '/admin/clientes/'
      path: '/clientes'
      fullPath: '/admin/clientes/'
      preLoaderRoute: typeof AdminClientesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/variacoes/nova': {
      id: '/admin/variacoes/nova'
      path: '/nova'
      fullPath: '/admin/variacoes/nova'
      preLoaderRoute: typeof AdminVariacoesNovaRouteImport
      parentRoute: typeof AdminVariacoesRoute
    }
    '/admin/solucoes/aplicativos': {
      id: '/admin/solucoes/aplicativos'
      path: '/solucoes/aplicativos'
      fullPath: '/admin/solucoes/aplicativos'
      preLoaderRoute: typeof AdminSolucoesAplicativosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/selos/novo': {
      id: '/admin/selos/novo'
      path: '/novo'
      fullPath: '/admin/selos/novo'
      preLoaderRoute: typeof AdminSelosNovoRouteImport
      parentRoute: typeof AdminSelosRoute
    }
    '/admin/produtos/precos': {
      id: '/admin/produtos/precos'
      path: '/precos'
      fullPath: '/admin/produtos/precos'
      preLoaderRoute: typeof AdminProdutosPrecosRouteImport
      parentRoute: typeof AdminProdutosRoute
    }
    '/admin/produtos/novo': {
      id: '/admin/produtos/novo'
      path: '/novo'
      fullPath: '/admin/produtos/novo'
      preLoaderRoute: typeof AdminProdutosNovoRouteImport
      parentRoute: typeof AdminProdutosRoute
    }
    '/admin/produtos/estoque': {
      id: '/admin/produtos/estoque'
      path: '/estoque'
      fullPath: '/admin/produtos/estoque'
      preLoaderRoute: typeof AdminProdutosEstoqueRouteImport
      parentRoute: typeof AdminProdutosRoute
    }
    '/admin/produtos/api-conexoes': {
      id: '/admin/produtos/api-conexoes'
      path: '/api-conexoes'
      fullPath: '/admin/produtos/api-conexoes'
      preLoaderRoute: typeof AdminProdutosApiConexoesRouteImport
      parentRoute: typeof AdminProdutosRoute
    }
    '/admin/pedidos/novo': {
      id: '/admin/pedidos/novo'
      path: '/pedidos/novo'
      fullPath: '/admin/pedidos/novo'
      preLoaderRoute: typeof AdminPedidosNovoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing/order-bumps': {
      id: '/admin/marketing/order-bumps'
      path: '/marketing/order-bumps'
      fullPath: '/admin/marketing/order-bumps'
      preLoaderRoute: typeof AdminMarketingOrderBumpsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing/compre-junto': {
      id: '/admin/marketing/compre-junto'
      path: '/marketing/compre-junto'
      fullPath: '/admin/marketing/compre-junto'
      preLoaderRoute: typeof AdminMarketingCompreJuntoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marcas/nova': {
      id: '/admin/marcas/nova'
      path: '/nova'
      fullPath: '/admin/marcas/nova'
      preLoaderRoute: typeof AdminMarcasNovaRouteImport
      parentRoute: typeof AdminMarcasRoute
    }
    '/admin/lojas/tabelas-precos': {
      id: '/admin/lojas/tabelas-precos'
      path: '/lojas/tabelas-precos'
      fullPath: '/admin/lojas/tabelas-precos'
      preLoaderRoute: typeof AdminLojasTabelasPrecosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lojas/paineis': {
      id: '/admin/lojas/paineis'
      path: '/lojas/paineis'
      fullPath: '/admin/lojas/paineis'
      preLoaderRoute: typeof AdminLojasPaineisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lojas/nova': {
      id: '/admin/lojas/nova'
      path: '/lojas/nova'
      fullPath: '/admin/lojas/nova'
      preLoaderRoute: typeof AdminLojasNovaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lojas/link-inscricao': {
      id: '/admin/lojas/link-inscricao'
      path: '/lojas/link-inscricao'
      fullPath: '/admin/lojas/link-inscricao'
      preLoaderRoute: typeof AdminLojasLinkInscricaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lojas/gerar': {
      id: '/admin/lojas/gerar'
      path: '/lojas/gerar'
      fullPath: '/admin/lojas/gerar'
      preLoaderRoute: typeof AdminLojasGerarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integracoes/webhooks': {
      id: '/admin/integracoes/webhooks'
      path: '/webhooks'
      fullPath: '/admin/integracoes/webhooks'
      preLoaderRoute: typeof AdminIntegracoesWebhooksRouteImport
      parentRoute: typeof AdminIntegracoesRoute
    }
    '/admin/integracoes/cofre': {
      id: '/admin/integracoes/cofre'
      path: '/cofre'
      fullPath: '/admin/integracoes/cofre'
      preLoaderRoute: typeof AdminIntegracoesCofreRouteImport
      parentRoute: typeof AdminIntegracoesRoute
    }
    '/admin/integracoes/api': {
      id: '/admin/integracoes/api'
      path: '/api'
      fullPath: '/admin/integracoes/api'
      preLoaderRoute: typeof AdminIntegracoesApiRouteImport
      parentRoute: typeof AdminIntegracoesRoute
    }
    '/admin/design/visual': {
      id: '/admin/design/visual'
      path: '/design/visual'
      fullPath: '/admin/design/visual'
      preLoaderRoute: typeof AdminDesignVisualRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/design/scripts': {
      id: '/admin/design/scripts'
      path: '/design/scripts'
      fullPath: '/admin/design/scripts'
      preLoaderRoute: typeof AdminDesignScriptsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/design/paginas': {
      id: '/admin/design/paginas'
      path: '/design/paginas'
      fullPath: '/admin/design/paginas'
      preLoaderRoute: typeof AdminDesignPaginasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/design/logo': {
      id: '/admin/design/logo'
      path: '/design/logo'
      fullPath: '/admin/design/logo'
      preLoaderRoute: typeof AdminDesignLogoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/design/cores': {
      id: '/admin/design/cores'
      path: '/design/cores'
      fullPath: '/admin/design/cores'
      preLoaderRoute: typeof AdminDesignCoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes/redirects': {
      id: '/admin/configuracoes/redirects'
      path: '/configuracoes/redirects'
      fullPath: '/admin/configuracoes/redirects'
      preLoaderRoute: typeof AdminConfiguracoesRedirectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes/pagamento': {
      id: '/admin/configuracoes/pagamento'
      path: '/configuracoes/pagamento'
      fullPath: '/admin/configuracoes/pagamento'
      preLoaderRoute: typeof AdminConfiguracoesPagamentoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes/loja': {
      id: '/admin/configuracoes/loja'
      path: '/configuracoes/loja'
      fullPath: '/admin/configuracoes/loja'
      preLoaderRoute: typeof AdminConfiguracoesLojaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes/dominios': {
      id: '/admin/configuracoes/dominios'
      path: '/configuracoes/dominios'
      fullPath: '/admin/configuracoes/dominios'
      preLoaderRoute: typeof AdminConfiguracoesDominiosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/canais/ifood': {
      id: '/admin/canais/ifood'
      path: '/canais/ifood'
      fullPath: '/admin/canais/ifood'
      preLoaderRoute: typeof AdminCanaisIfoodRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/canais/google-shopping': {
      id: '/admin/canais/google-shopping'
      path: '/canais/google-shopping'
      fullPath: '/admin/canais/google-shopping'
      preLoaderRoute: typeof AdminCanaisGoogleShoppingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/canais/farmaciasapp': {
      id: '/admin/canais/farmaciasapp'
      path: '/canais/farmaciasapp'
      fullPath: '/admin/canais/farmaciasapp'
      preLoaderRoute: typeof AdminCanaisFarmaciasappRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_store/v/$slug': {
      id: '/_store/v/$slug'
      path: '/v/$slug'
      fullPath: '/v/$slug'
      preLoaderRoute: typeof StoreVSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/pagina/$slug': {
      id: '/_store/pagina/$slug'
      path: '/pagina/$slug'
      fullPath: '/pagina/$slug'
      preLoaderRoute: typeof StorePaginaSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/p/$slug': {
      id: '/_store/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof StorePSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/m/$slug': {
      id: '/_store/m/$slug'
      path: '/m/$slug'
      fullPath: '/m/$slug'
      preLoaderRoute: typeof StoreMSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/c/$slug': {
      id: '/_store/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof StoreCSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/ajuda/$page': {
      id: '/_store/ajuda/$page'
      path: '/ajuda/$page'
      fullPath: '/ajuda/$page'
      preLoaderRoute: typeof StoreAjudaPageRouteImport
      parentRoute: typeof StoreRoute
    }
    '/admin/marketing/promocoes/': {
      id: '/admin/marketing/promocoes/'
      path: '/marketing/promocoes'
      fullPath: '/admin/marketing/promocoes/'
      preLoaderRoute: typeof AdminMarketingPromocoesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing/cupons/': {
      id: '/admin/marketing/cupons/'
      path: '/marketing/cupons'
      fullPath: '/admin/marketing/cupons/'
      preLoaderRoute: typeof AdminMarketingCuponsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing/promocoes/nova': {
      id: '/admin/marketing/promocoes/nova'
      path: '/marketing/promocoes/nova'
      fullPath: '/admin/marketing/promocoes/nova'
      preLoaderRoute: typeof AdminMarketingPromocoesNovaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing/cupons/novo': {
      id: '/admin/marketing/cupons/novo'
      path: '/marketing/cupons/novo'
      fullPath: '/admin/marketing/cupons/novo'
      preLoaderRoute: typeof AdminMarketingCuponsNovoRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface StoreRouteChildren {
  StoreStoreSlugRoute: typeof StoreStoreSlugRoute
  StoreBuscaRoute: typeof StoreBuscaRoute
  StoreCadastroRoute: typeof StoreCadastroRoute
  StoreCartRoute: typeof StoreCartRoute
  StoreCheckoutRoute: typeof StoreCheckoutRoute
  StoreCompartilhadoRoute: typeof StoreCompartilhadoRoute
  StoreFaqRoute: typeof StoreFaqRoute
  StoreLoginRoute: typeof StoreLoginRoute
  StoreMapaSiteRoute: typeof StoreMapaSiteRoute
  StorePedidosRoute: typeof StorePedidosRoute
  StorePerfilRoute: typeof StorePerfilRoute
  StoreAjudaPageRoute: typeof StoreAjudaPageRoute
  StoreCSlugRoute: typeof StoreCSlugRoute
  StoreMSlugRoute: typeof StoreMSlugRoute
  StorePSlugRoute: typeof StorePSlugRoute
  StorePaginaSlugRoute: typeof StorePaginaSlugRoute
  StoreVSlugRoute: typeof StoreVSlugRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreStoreSlugRoute: StoreStoreSlugRoute,
  StoreBuscaRoute: StoreBuscaRoute,
  StoreCadastroRoute: StoreCadastroRoute,
  StoreCartRoute: StoreCartRoute,
  StoreCheckoutRoute: StoreCheckoutRoute,
  StoreCompartilhadoRoute: StoreCompartilhadoRoute,
  StoreFaqRoute: StoreFaqRoute,
  StoreLoginRoute: StoreLoginRoute,
  StoreMapaSiteRoute: StoreMapaSiteRoute,
  StorePedidosRoute: StorePedidosRoute,
  StorePerfilRoute: StorePerfilRoute,
  StoreAjudaPageRoute: StoreAjudaPageRoute,
  StoreCSlugRoute: StoreCSlugRoute,
  StoreMSlugRoute: StoreMSlugRoute,
  StorePSlugRoute: StorePSlugRoute,
  StorePaginaSlugRoute: StorePaginaSlugRoute,
  StoreVSlugRoute: StoreVSlugRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

interface AdminIntegracoesRouteChildren {
  AdminIntegracoesApiRoute: typeof AdminIntegracoesApiRoute
  AdminIntegracoesCofreRoute: typeof AdminIntegracoesCofreRoute
  AdminIntegracoesWebhooksRoute: typeof AdminIntegracoesWebhooksRoute
}

const AdminIntegracoesRouteChildren: AdminIntegracoesRouteChildren = {
  AdminIntegracoesApiRoute: AdminIntegracoesApiRoute,
  AdminIntegracoesCofreRoute: AdminIntegracoesCofreRoute,
  AdminIntegracoesWebhooksRoute: AdminIntegracoesWebhooksRoute,
}

const AdminIntegracoesRouteWithChildren =
  AdminIntegracoesRoute._addFileChildren(AdminIntegracoesRouteChildren)

interface AdminMarcasRouteChildren {
  AdminMarcasNovaRoute: typeof AdminMarcasNovaRoute
}

const AdminMarcasRouteChildren: AdminMarcasRouteChildren = {
  AdminMarcasNovaRoute: AdminMarcasNovaRoute,
}

const AdminMarcasRouteWithChildren = AdminMarcasRoute._addFileChildren(
  AdminMarcasRouteChildren,
)

interface AdminProdutosRouteChildren {
  AdminProdutosApiConexoesRoute: typeof AdminProdutosApiConexoesRoute
  AdminProdutosEstoqueRoute: typeof AdminProdutosEstoqueRoute
  AdminProdutosNovoRoute: typeof AdminProdutosNovoRoute
  AdminProdutosPrecosRoute: typeof AdminProdutosPrecosRoute
}

const AdminProdutosRouteChildren: AdminProdutosRouteChildren = {
  AdminProdutosApiConexoesRoute: AdminProdutosApiConexoesRoute,
  AdminProdutosEstoqueRoute: AdminProdutosEstoqueRoute,
  AdminProdutosNovoRoute: AdminProdutosNovoRoute,
  AdminProdutosPrecosRoute: AdminProdutosPrecosRoute,
}

const AdminProdutosRouteWithChildren = AdminProdutosRoute._addFileChildren(
  AdminProdutosRouteChildren,
)

interface AdminSelosRouteChildren {
  AdminSelosNovoRoute: typeof AdminSelosNovoRoute
}

const AdminSelosRouteChildren: AdminSelosRouteChildren = {
  AdminSelosNovoRoute: AdminSelosNovoRoute,
}

const AdminSelosRouteWithChildren = AdminSelosRoute._addFileChildren(
  AdminSelosRouteChildren,
)

interface AdminVariacoesRouteChildren {
  AdminVariacoesNovaRoute: typeof AdminVariacoesNovaRoute
}

const AdminVariacoesRouteChildren: AdminVariacoesRouteChildren = {
  AdminVariacoesNovaRoute: AdminVariacoesNovaRoute,
}

const AdminVariacoesRouteWithChildren = AdminVariacoesRoute._addFileChildren(
  AdminVariacoesRouteChildren,
)

interface AdminRouteChildren {
  AdminAoVivoRoute: typeof AdminAoVivoRoute
  AdminAvaliacoesRoute: typeof AdminAvaliacoesRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCarrinhosAbandonadosRoute: typeof AdminCarrinhosAbandonadosRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminColecoesRoute: typeof AdminColecoesRoute
  AdminDescontosRoute: typeof AdminDescontosRoute
  AdminEstoqueRoute: typeof AdminEstoqueRoute
  AdminFiltrosRoute: typeof AdminFiltrosRoute
  AdminIntegracoesRoute: typeof AdminIntegracoesRouteWithChildren
  AdminLinksCarrinhoRoute: typeof AdminLinksCarrinhoRoute
  AdminListaEsperaRoute: typeof AdminListaEsperaRoute
  AdminLogisticaRoute: typeof AdminLogisticaRoute
  AdminMarcasRoute: typeof AdminMarcasRouteWithChildren
  AdminMetricasRoute: typeof AdminMetricasRoute
  AdminMinhaLogisticaRoute: typeof AdminMinhaLogisticaRoute
  AdminPaginasInformativasRoute: typeof AdminPaginasInformativasRoute
  AdminPbmsRoute: typeof AdminPbmsRoute
  AdminPerguntasRoute: typeof AdminPerguntasRoute
  AdminProdutosRoute: typeof AdminProdutosRouteWithChildren
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminSelosRoute: typeof AdminSelosRouteWithChildren
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminVariacoesRoute: typeof AdminVariacoesRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCanaisFarmaciasappRoute: typeof AdminCanaisFarmaciasappRoute
  AdminCanaisGoogleShoppingRoute: typeof AdminCanaisGoogleShoppingRoute
  AdminCanaisIfoodRoute: typeof AdminCanaisIfoodRoute
  AdminConfiguracoesDominiosRoute: typeof AdminConfiguracoesDominiosRoute
  AdminConfiguracoesLojaRoute: typeof AdminConfiguracoesLojaRoute
  AdminConfiguracoesPagamentoRoute: typeof AdminConfiguracoesPagamentoRoute
  AdminConfiguracoesRedirectsRoute: typeof AdminConfiguracoesRedirectsRoute
  AdminDesignCoresRoute: typeof AdminDesignCoresRoute
  AdminDesignLogoRoute: typeof AdminDesignLogoRoute
  AdminDesignPaginasRoute: typeof AdminDesignPaginasRoute
  AdminDesignScriptsRoute: typeof AdminDesignScriptsRoute
  AdminDesignVisualRoute: typeof AdminDesignVisualRoute
  AdminLojasGerarRoute: typeof AdminLojasGerarRoute
  AdminLojasLinkInscricaoRoute: typeof AdminLojasLinkInscricaoRoute
  AdminLojasNovaRoute: typeof AdminLojasNovaRoute
  AdminLojasPaineisRoute: typeof AdminLojasPaineisRoute
  AdminLojasTabelasPrecosRoute: typeof AdminLojasTabelasPrecosRoute
  AdminMarketingCompreJuntoRoute: typeof AdminMarketingCompreJuntoRoute
  AdminMarketingOrderBumpsRoute: typeof AdminMarketingOrderBumpsRoute
  AdminPedidosNovoRoute: typeof AdminPedidosNovoRoute
  AdminSolucoesAplicativosRoute: typeof AdminSolucoesAplicativosRoute
  AdminClientesIndexRoute: typeof AdminClientesIndexRoute
  AdminConfiguracoesIndexRoute: typeof AdminConfiguracoesIndexRoute
  AdminDesignIndexRoute: typeof AdminDesignIndexRoute
  AdminLojasIndexRoute: typeof AdminLojasIndexRoute
  AdminPedidosIndexRoute: typeof AdminPedidosIndexRoute
  AdminMarketingCuponsNovoRoute: typeof AdminMarketingCuponsNovoRoute
  AdminMarketingPromocoesNovaRoute: typeof AdminMarketingPromocoesNovaRoute
  AdminMarketingCuponsIndexRoute: typeof AdminMarketingCuponsIndexRoute
  AdminMarketingPromocoesIndexRoute: typeof AdminMarketingPromocoesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAoVivoRoute: AdminAoVivoRoute,
  AdminAvaliacoesRoute: AdminAvaliacoesRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminCarrinhosAbandonadosRoute: AdminCarrinhosAbandonadosRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminColecoesRoute: AdminColecoesRoute,
  AdminDescontosRoute: AdminDescontosRoute,
  AdminEstoqueRoute: AdminEstoqueRoute,
  AdminFiltrosRoute: AdminFiltrosRoute,
  AdminIntegracoesRoute: AdminIntegracoesRouteWithChildren,
  AdminLinksCarrinhoRoute: AdminLinksCarrinhoRoute,
  AdminListaEsperaRoute: AdminListaEsperaRoute,
  AdminLogisticaRoute: AdminLogisticaRoute,
  AdminMarcasRoute: AdminMarcasRouteWithChildren,
  AdminMetricasRoute: AdminMetricasRoute,
  AdminMinhaLogisticaRoute: AdminMinhaLogisticaRoute,
  AdminPaginasInformativasRoute: AdminPaginasInformativasRoute,
  AdminPbmsRoute: AdminPbmsRoute,
  AdminPerguntasRoute: AdminPerguntasRoute,
  AdminProdutosRoute: AdminProdutosRouteWithChildren,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminSelosRoute: AdminSelosRouteWithChildren,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminVariacoesRoute: AdminVariacoesRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminCanaisFarmaciasappRoute: AdminCanaisFarmaciasappRoute,
  AdminCanaisGoogleShoppingRoute: AdminCanaisGoogleShoppingRoute,
  AdminCanaisIfoodRoute: AdminCanaisIfoodRoute,
  AdminConfiguracoesDominiosRoute: AdminConfiguracoesDominiosRoute,
  AdminConfiguracoesLojaRoute: AdminConfiguracoesLojaRoute,
  AdminConfiguracoesPagamentoRoute: AdminConfiguracoesPagamentoRoute,
  AdminConfiguracoesRedirectsRoute: AdminConfiguracoesRedirectsRoute,
  AdminDesignCoresRoute: AdminDesignCoresRoute,
  AdminDesignLogoRoute: AdminDesignLogoRoute,
  AdminDesignPaginasRoute: AdminDesignPaginasRoute,
  AdminDesignScriptsRoute: AdminDesignScriptsRoute,
  AdminDesignVisualRoute: AdminDesignVisualRoute,
  AdminLojasGerarRoute: AdminLojasGerarRoute,
  AdminLojasLinkInscricaoRoute: AdminLojasLinkInscricaoRoute,
  AdminLojasNovaRoute: AdminLojasNovaRoute,
  AdminLojasPaineisRoute: AdminLojasPaineisRoute,
  AdminLojasTabelasPrecosRoute: AdminLojasTabelasPrecosRoute,
  AdminMarketingCompreJuntoRoute: AdminMarketingCompreJuntoRoute,
  AdminMarketingOrderBumpsRoute: AdminMarketingOrderBumpsRoute,
  AdminPedidosNovoRoute: AdminPedidosNovoRoute,
  AdminSolucoesAplicativosRoute: AdminSolucoesAplicativosRoute,
  AdminClientesIndexRoute: AdminClientesIndexRoute,
  AdminConfiguracoesIndexRoute: AdminConfiguracoesIndexRoute,
  AdminDesignIndexRoute: AdminDesignIndexRoute,
  AdminLojasIndexRoute: AdminLojasIndexRoute,
  AdminPedidosIndexRoute: AdminPedidosIndexRoute,
  AdminMarketingCuponsNovoRoute: AdminMarketingCuponsNovoRoute,
  AdminMarketingPromocoesNovaRoute: AdminMarketingPromocoesNovaRoute,
  AdminMarketingCuponsIndexRoute: AdminMarketingCuponsIndexRoute,
  AdminMarketingPromocoesIndexRoute: AdminMarketingPromocoesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StoreRoute: StoreRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  InscricaoTokenRoute: InscricaoTokenRoute,
  PainelLojaLojaIdRoute: PainelLojaLojaIdRoute,
  PainelLojaOldRoute: PainelLojaOldRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
