// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    if (!headers.has('apikey')) {
      headers.set('apikey', supabaseKey);
    }
    if (!headers.has('Authorization') || !headers.get('Authorization')) {
      headers.set('Authorization', `Bearer ${supabaseKey}`);
    }

    return fetch(input, { ...init, headers });
  };
}


// Safe WebSocket wrapper to prevent browser Mixed Content crashes when connecting to ws:// from https://
function getSafeWebSocketTransport() {
  if (typeof window === 'undefined') return undefined;
  
  return class SafeWebSocket {
    private ws: WebSocket | null = null;
    public readyState: number = 3; // CLOSED
    public onopen: ((ev: Event) => any) | null = null;
    public onclose: ((ev: CloseEvent) => any) | null = null;
    public onerror: ((ev: Event) => any) | null = null;
    public onmessage: ((ev: MessageEvent) => any) | null = null;

    constructor(url: string | URL, protocols?: string | string[]) {
      const urlStr = String(url);
      const isHttpsPage = typeof window !== 'undefined' && window.location.protocol === 'https:';
      
      // If we are on HTTPS and WebSocket is ws:// or points to HTTP proxy, gracefully bypass
      if (urlStr.includes('/api/supabase') || (isHttpsPage && urlStr.startsWith('ws://')) || (isHttpsPage && urlStr.includes(window.location.host))) {
        this.readyState = 3;
        setTimeout(() => {
          if (this.onclose) this.onclose(new CloseEvent('close', { code: 1000, reason: 'Realtime disabled over HTTP/proxy', wasClean: true }));
        }, 0);
        return;
      }

      try {
        const wsInstance = new WebSocket(url, protocols);
        this.ws = wsInstance;
        this.readyState = wsInstance.readyState;

        wsInstance.onopen = (ev) => {
          this.readyState = wsInstance.readyState;
          if (this.onopen) this.onopen(ev);
        };
        wsInstance.onclose = (ev) => {
          this.readyState = wsInstance.readyState;
          if (this.onclose) this.onclose(ev);
        };
        wsInstance.onerror = (ev) => {
          this.readyState = wsInstance.readyState;
          if (this.onerror) this.onerror(ev);
        };
        wsInstance.onmessage = (ev) => {
          if (this.onmessage) this.onmessage(ev);
        };
      } catch (err) {
        console.warn('[Supabase Realtime] Falha ao instanciar WebSocket:', err);
        this.readyState = 3;
        setTimeout(() => {
          if (this.onerror) this.onerror(new Event('error'));
          if (this.onclose) this.onclose(new CloseEvent('close', { code: 1006, reason: 'Failed to construct WebSocket', wasClean: false }));
        }, 0);
      }
    }

    send(data: any) {
      if (this.ws && this.ws.readyState === WebSocket.OPEN) {
        this.ws.send(data);
      }
    }

    close(code?: number, reason?: string) {
      if (this.ws) {
        this.ws.close(code, reason);
      }
      this.readyState = 3;
    }

    addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions) {
      if (this.ws) {
        this.ws.addEventListener(type, listener, options);
      }
    }

    removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions) {
      if (this.ws) {
        this.ws.removeEventListener(type, listener, options);
      }
    }
  };
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  let effectiveUrl = SUPABASE_URL;
  if (typeof window !== 'undefined' && window.location.protocol === 'https:' && SUPABASE_URL.startsWith('http://')) {
    effectiveUrl = `${window.location.origin}/api/supabase`;
  }

  const safeTransport = getSafeWebSocketTransport();

  // Limpeza preventiva: remove tokens legados do localStorage para evitar persistência indevida
  if (typeof window !== 'undefined') {
    try {
      localStorage.removeItem('sb-token');
      localStorage.removeItem('supabase.auth.token');
    } catch {}
  }

  return createClient<Database>(effectiveUrl, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      // Armazena a sessão exclusivamente em sessionStorage (limpo automaticamente ao fechar a aba)
      storage: typeof window !== 'undefined' ? sessionStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
    realtime: {
      transport: safeTransport as any,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

